jobs:
- job: TestAppModules
  displayName: Test App Modules

  variables:
  - name: TEST_RESULTS_PATH
    value: $(Build.SourcesDirectory)/junit.xml
  - name: COVERAGE_PATH
    value: $(Build.SourcesDirectory)/coverage/cobertura-coverage.xml

  steps:
  - template: step-install-node.yml
  
  - script: npm install
    displayName: Restore npm modules
    workingDirectory: $(NODE_CODE_PATH)
  
  - script: npm test
    displayName: Run jest tests with coverage
    workingDirectory: $(NODE_CODE_PATH)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish unit test results
    inputs:
      testRunTitle: Node Unit Test Results
      testResultsFormat: JUnit
      testResultsFiles: $(TEST_RESULTS_PATH)

  - task: PublishCodeCoverageResults@1
    displayName: Publish unit test code coverage
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: $(COVERAGE_PATH)
      